import {
  BlockKind,
  FieldKind,
  Templates,
  TemplateTypes,
} from "@/interfaces/enum";

export const defaultTemplates = {
  [Templates.Text]: {
    id: Templates.Text,
    type: TemplateTypes.Block,
    kind: BlockKind.Text,
  },
  [Templates.Image]: {
    id: Templates.Image,
    type: TemplateTypes.Block,
    kind: BlockKind.Image,
  },
  [Templates.Video]: {
    id: Templates.Video,
    type: TemplateTypes.Block,
    kind: BlockKind.Video,
  },
  [Templates.PageBreak]: {
    id: Templates.PageBreak,
    type: TemplateTypes.Block,
    kind: BlockKind.PageBreak,
  },
  [Templates.TableOfContents]: {
    id: Templates.TableOfContents,
    type: TemplateTypes.Block,
    kind: BlockKind.TableOfContents,
  },
  [Templates.Table]: {
    id: Templates.Table,
    type: TemplateTypes.Block,
    kind: BlockKind.Table,
  },
  [Templates.Textarea]: {
    id: Templates.Textarea,
    type: TemplateTypes.Field,
    kind: FieldKind.TextArea,
    propsSchema: {
      width: 171,
      height: 33,
      minWidth: 25,
      minHeight: 15,
      resizeWidth: true,
      resizeHeight: true,
    },
  },
  [Templates.Signature]: {
    id: Templates.Signature,
    type: TemplateTypes.Field,
    kind: FieldKind.Signature,
    propsSchema: {
      width: 161,
      height: 61,
      minWidth: 25,
      minHeight: 15,
      resizeWidth: true,
      resizeHeight: true,
    },
  },
  [Templates.Initials]: {
    id: Templates.Initials,
    type: TemplateTypes.Field,
    kind: FieldKind.Initials,
    propsSchema: {
      width: 100,
      height: 71,
      minWidth: 25,
      minHeight: 15,
      resizeWidth: true,
      resizeHeight: true,
    },
  },
  [Templates.Checkbox]: {
    id: Templates.Checkbox,
    type: TemplateTypes.Field,
    kind: FieldKind.Checkbox,
    propsSchema: {
      width: 25,
      height: 25,
      minWidth: 15,
      minHeight: 15,
      resizeWidth: true,
      resizeHeight: true,
    },
  },
  [Templates.Date]: {
    id: Templates.Date,
    type: TemplateTypes.Field,
    kind: FieldKind.Date,
    propsSchema: {
      width: 150,
      height: 28,
      minWidth: 25,
      minHeight: 28,
      resizeWidth: true,
      resizeHeight: false,
    },
  },
  [Templates.Stamp]: {
    id: Templates.Stamp,
    type: TemplateTypes.Field,
    kind: FieldKind.Stamp,
    propsSchema: {
      width: 130,
      height: 130,
      minWidth: 25,
      minHeight: 25,
      resizeWidth: true,
      resizeHeight: true,
    },
  },
  [Templates.CollectFiles]: {
    id: Templates.CollectFiles,
    type: TemplateTypes.Field,
    kind: FieldKind.CollectFiles,
    propsSchema: {
      width: 180,
      height: 29,
      minWidth: 25,
      minHeight: 29,
      resizeWidth: true,
      resizeHeight: false,
    },
  },
  [Templates.Radio]: {
    id: Templates.Radio,
    type: TemplateTypes.Field,
    kind: FieldKind.Radio,
    propsSchema: {
      width: 100,
      height: 86,
      resizeWidth: false,
      resizeHeight: false,
    },
  },
  [Templates.Dropdown]: {
    id: Templates.Dropdown,
    type: TemplateTypes.Field,
    kind: FieldKind.Dropdown,
    propsSchema: {
      width: 160,
      height: 28,
      minWidth: 25,
      minHeight: 28,
      resizeWidth: true,
      resizeHeight: false,
    },
  },
};
