// app/pdf/print/page.tsx
export const dynamic = "force-dynamic"; // always SSR (optional)
export const revalidate = 0; // no cache (optional)

export default function PrintPage() {
  // hard-coded backend content + Tailwind
  return (
    <html lang="en">
      <head />
      <body className="prose prose-slate max-w-none p-8">
        <h1 className="mb-4 text-3xl font-bold">Service Agreement</h1>
        <p>
          This Agreement (“Agreement”) is made between{" "}
          <strong>Acme Sp. z o.o.</strong> and
          <strong> John Doe</strong>.
        </p>

        <h2 className="mt-8 text-xl font-semibold">1. Scope</h2>
        <ul className="list-disc pl-6">
          <li>Design and implementation of the web application.</li>
          <li>Maintenance and support for 6 months.</li>
        </ul>

        <div className="page-break" />

        <h2 className="mt-8 text-xl font-semibold">2. Fees</h2>
        <p>
          Total fee: <strong>20,000 PLN</strong>.
        </p>
        {/*  */}
        <article className="prose prose-slate max-w-none p-8">
          <header className="mb-6">
            <h1 className="text-3xl font-bold">Service Agreement</h1>
            <p className="text-sm text-slate-500">
              Generated by the server • {new Date().toLocaleDateString("pl-PL")}
            </p>
          </header>

          <section className="space-y-4">
            <p>
              This Agreement (“Agreement”) is made between{" "}
              <strong>Acme Sp. z o.o.</strong> and
              <strong> John Doe</strong>. The parties agree to the following
              terms:
            </p>

            <h2 className="mt-8 text-xl font-semibold">1. Scope</h2>
            <ul className="list-disc pl-6">
              <li>Design and implementation of the web application.</li>
              <li>Maintenance and support for 6 months.</li>
            </ul>

            <h2 className="mt-8 text-xl font-semibold">2. Fees</h2>
            <p>
              Total fee: <strong>20,000 PLN</strong>, payable in two equal
              installments.
            </p>

            <div className="page-break" />

            <h2 className="mt-8 text-xl font-semibold">3. Acceptance</h2>
            <p>
              Work is deemed accepted after user acceptance testing (UAT) with
              written confirmation.
            </p>

            <h2 className="mt-8 text-xl font-semibold">4. Signatures</h2>
            <table className="w-full border-separate border-spacing-y-6">
              <tbody>
                <tr className="align-top">
                  <td className="w-1/2 pr-6">
                    <div className="avoid-break flex h-24 items-end rounded-lg border p-4">
                      Client signature
                    </div>
                    <p className="mt-2 text-sm text-slate-500">John Doe</p>
                  </td>
                  <td className="w-1/2 pl-6">
                    <div className="avoid-break flex h-24 items-end rounded-lg border p-4">
                      Company signature
                    </div>
                    <p className="mt-2 text-sm text-slate-500">
                      Acme Sp. z o.o.
                    </p>
                  </td>
                </tr>
              </tbody>
            </table>
          </section>
        </article>
      </body>
    </html>
  );
}
